server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: HYBRID-BOOKING-SERVICE
          uri: lb://HYBRID-BOOKING-SERVICE
          predicates:
            - Path=/hybrid-booking/**
        - id: MEDICAL-HISTORY-SERVICE
          uri: lb://MEDICAL-HISTORY-SERVICE
          predicates:
            - Path=/medical-history/**
        - id: HOSPITAL-SERVICE
          uri: lb://HOSPITAL-SERVICE
          predicates:
            - Path=/hospital/**


eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://docs.diordev.me:8761/eureka/}
    instance:
      preferIpAddress: true
