server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
        - id: HYBRID-BOOKING-SERVICE
          uri: lb://HYBRID_BOOKING-SERVICE
          predicates:
            - Path=/hybrid-booking/**


eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true
